
#ifdef GET_DIAG_ARRAYS
static const short DiagSubGroup0[] = { 72, -1 };
static const short DiagArray1[] = { diag::warn_pragma_message, -1 };
static const short DiagArray2[] = { diag::pp_hash_warning, -1 };
static const short DiagArray3[] = { diag::err_cfstring_literal_not_string_constant, diag::warn_cfstring_truncated, -1 };
static const short DiagArray6[] = { diag::ext_typecheck_addrof_class_temporary, -1 };
static const short DiagSubGroup8[] = { 126, 154, -1 };
static const short DiagArray9[] = { diag::ext_nested_name_member_ref_lookup_ambiguous, -1 };
static const short DiagArray10[] = { diag::warn_incompatible_analyzer_plugin_api, -1 };
static const short DiagArray11[] = { diag::err_arc_indirect_no_ownership, -1 };
static const short DiagSubGroup11[] = { 12, 16, 15, 13, -1 };
static const short DiagArray12[] = { diag::warn_arc_non_pod_class_with_object_member, diag::warn_arc_trivial_member_function_with_object_member, diag::warn_err_new_delete_object_array, -1 };
static const short DiagArray13[] = { diag::warn_arc_object_memaccess, -1 };
static const short DiagArray14[] = { diag::warn_arc_perform_selector_leaks, -1 };
static const short DiagArray15[] = { diag::warn_arc_retain_cycle, -1 };
static const short DiagArray16[] = { diag::warn_arc_retained_assign, diag::warn_arc_retained_property_assign, -1 };
static const short DiagArray17[] = { diag::warn_array_index_exceeds_bounds, diag::warn_array_index_precedes_bounds, -1 };
static const short DiagArray18[] = { diag::warn_ptr_arith_exceeds_bounds, diag::warn_ptr_arith_precedes_bounds, -1 };
static const short DiagSubGroup19[] = { 91, 51, -1 };
static const short DiagArray20[] = { diag::warn_atomic_property_rule, -1 };
static const short DiagArray21[] = { diag::warn_unknown_attribute_ignored, -1 };
static const short DiagArray24[] = { diag::ext_rvalue_to_reference_access_ctor, diag::ext_rvalue_to_reference_temp_copy_no_viable, -1 };
static const short DiagArray25[] = { diag::warn_bitwise_and_in_bitwise_or, -1 };
static const short DiagArray26[] = { diag::warn_impcast_bool_to_null_pointer, -1 };
static const short DiagArray27[] = { diag::pp_redef_builtin_macro, -1 };
static const short DiagArray28[] = { diag::ext_empty_struct_union, -1 };
static const short DiagSubGroup29[] = { 32, -1 };
static const short DiagSubGroup30[] = { 33, -1 };
static const short DiagSubGroup31[] = { 34, -1 };
static const short DiagArray32[] = { diag::warn_auto_storage_class, diag::warn_cxx11_keyword, diag::warn_explicit_instantiation_must_be_global_0x, diag::warn_explicit_instantiation_out_of_scope_0x, diag::warn_explicit_instantiation_unqualified_wrong_namespace_0x, -1 };
static const short DiagSubGroup32[] = { 34, -1 };
static const short DiagArray33[] = { diag::ext_alias_declaration, diag::ext_array_size_conversion, diag::ext_auto_type_specifier, diag::ext_explicit_instantiation_after_specialization, diag::ext_for_range, diag::ext_generalized_initializer_lists, diag::ext_inline_namespace, diag::ext_nonclass_type_friend, diag::ext_override_control_keyword, diag::ext_ref_qualifier, diag::ext_rvalue_reference, diag::ext_template_outside_of_template, diag::ext_template_parameter_default_in_function_template, diag::ext_template_spec_decl_out_of_scope, diag::ext_template_spec_decl_out_of_scope_global, diag::ext_typename_outside_of_template, diag::ext_unelaborated_friend_type, diag::ext_variadic_templates, diag::warn_defaulted_function_accepted_as_extension, diag::warn_deleted_function_accepted_as_extension, diag::warn_explicit_conversion_functions, diag::warn_nonstatic_member_init_accepted_as_extension, -1 };
static const short DiagArray34[] = { diag::warn_init_list_constant_narrowing, diag::warn_init_list_variable_narrowing, -1 };
static const short DiagArray35[] = { diag::warn_cxx98_compat_alignas, diag::warn_cxx98_compat_attribute, diag::warn_cxx98_compat_less_colon_colon, diag::warn_cxx98_compat_raw_string_literal, diag::warn_cxx98_compat_unicode_literal, diag::warn_cxx98_compat_variadic_templates, -1 };
static const short DiagArray36[] = { diag::warn_cxx98_compat_empty_fnmacro_arg, diag::warn_cxx98_compat_longlong, diag::warn_cxx98_compat_pp_line_too_big, diag::warn_cxx98_compat_variadic_macro, -1 };
static const short DiagSubGroup36[] = { 35, -1 };
static const short DiagArray37[] = { diag::ext_c1x_alignas, diag::ext_c1x_generic_selection, diag::ext_c1x_static_assert, -1 };
static const short DiagArray38[] = { diag::warn_cast_align, -1 };
static const short DiagArray41[] = { diag::warn_subscript_is_char, -1 };
static const short DiagArray42[] = { diag::escaped_newline_block_comment_end, diag::ext_bcpl_comment, diag::ext_multi_line_bcpl_comment, diag::warn_nested_block_comment, -1 };
static const short DiagSubGroup43[] = { 42, -1 };
static const short DiagArray44[] = { diag::ext_complex_component_init, -1 };
static const short DiagArray45[] = { diag::warn_typecheck_cond_pointer_integer_mismatch, -1 };
static const short DiagArray46[] = { diag::warn_maybe_uninit_var, diag::warn_maybe_uninit_var_captured_by_block, -1 };
static const short DiagArray47[] = { diag::warn_impcast_bitfield_precision_constant, diag::warn_impcast_integer_precision_constant, -1 };
static const short DiagArray48[] = { diag::warn_logical_instead_of_bitwise, -1 };
static const short DiagArray49[] = { diag::warn_impcast_complex_scalar, diag::warn_impcast_different_enum_types, diag::warn_impcast_float_integer, diag::warn_impcast_float_precision, diag::warn_impcast_integer_precision, diag::warn_impcast_null_pointer_to_integer, diag::warn_impcast_vector_scalar, diag::warn_template_arg_negative, diag::warn_template_arg_too_large, -1 };
static const short DiagSubGroup49[] = { 178, 47, 107, 199, 180, 26, -1 };
static const short DiagArray51[] = { diag::warn_default_atomic_custom_getter_setter, -1 };
static const short DiagArray52[] = { diag::warn_bind_ref_member_to_parameter, diag::warn_bind_ref_member_to_temporary, diag::warn_init_ptr_member_to_parameter_addr, -1 };
static const short DiagArray53[] = { diag::ext_mixed_decls_code, -1 };
static const short DiagArray54[] = { diag::warn_default_arg_makes_ctor_special, -1 };
static const short DiagArray55[] = { diag::note_it_delegates_to, diag::note_which_delegates_to, diag::warn_delegating_ctor_cycle, -1 };
static const short DiagArray56[] = { diag::warn_delete_abstract_non_virtual_dtor, diag::warn_delete_non_virtual_dtor, -1 };
static const short DiagArray57[] = { diag::warn_access_decl_deprecated, diag::warn_drv_treating_input_as_cxx, diag::warn_increment_bool, diag::warn_vector_long_decl_spec_combination, -1 };
static const short DiagSubGroup57[] = { 58, -1 };
static const short DiagArray58[] = { diag::warn_deprecated, diag::warn_deprecated_fwdclass_message, diag::warn_deprecated_message, -1 };
static const short DiagArray59[] = { diag::warn_deprecated_def, -1 };
static const short DiagArray60[] = { diag::warn_deprecated_string_literal_conversion, -1 };
static const short DiagArray63[] = { diag::warn_conflicting_param_modifiers, diag::warn_conflicting_ret_type_modifiers, -1 };
static const short DiagArray65[] = { diag::warn_method_param_declaration, -1 };
static const short DiagArray66[] = { diag::warn_dyn_class_memaccess, -1 };
static const short DiagArray68[] = { diag::warn_empty_if_body, -1 };
static const short DiagSubGroup69[] = { 73, -1 };
static const short DiagArray70[] = { diag::warn_comparison_of_mixed_enum_types, -1 };
static const short DiagArray71[] = { diag::warn_exit_time_destructor, -1 };
static const short DiagSubGroup72[] = { 119, 89, 98, 169, 122, 179, 232, -1 };
static const short DiagArray73[] = { diag::ext_pp_extra_tokens_at_eol, -1 };
static const short DiagArray74[] = { diag::warn_floatingpoint_eq, -1 };
static const short DiagArray75[] = { diag::warn_format_invalid_positional_specifier, diag::warn_format_mix_positional_nonpositional_args, diag::warn_format_nonsensical_length, diag::warn_format_string_is_wide_literal, diag::warn_format_zero_positional_specifier, diag::warn_missing_format_string, diag::warn_printf_asterisk_wrong_type, diag::warn_printf_conversion_argument_type_mismatch, diag::warn_printf_format_string_contains_null_char, diag::warn_printf_ignored_flag, diag::warn_printf_incomplete_specifier, diag::warn_printf_insufficient_data_args, diag::warn_printf_nonsensical_flag, diag::warn_printf_nonsensical_optional_amount, diag::warn_printf_positional_arg_exceeds_data_args, diag::warn_scanf_nonzero_width, diag::warn_scanf_scanlist_incomplete, -1 };
static const short DiagSubGroup75[] = { 76, 81, 134, 79, 80, 77, -1 };
static const short DiagArray76[] = { diag::warn_printf_data_arg_not_used, -1 };
static const short DiagArray77[] = { diag::warn_format_invalid_conversion, -1 };
static const short DiagArray78[] = { diag::warn_format_nonliteral, -1 };
static const short DiagSubGroup78[] = { 79, -1 };
static const short DiagArray79[] = { diag::warn_format_nonliteral_noargs, diag::warn_printf_write_back, -1 };
static const short DiagArray81[] = { diag::warn_empty_format_string, -1 };
static const short DiagSubGroup82[] = { 78, 79, 80, -1 };
static const short DiagArray83[] = { diag::ext_four_char_character_literal, -1 };
static const short DiagArray84[] = { diag::warn_global_constructor, diag::warn_global_destructor, -1 };
static const short DiagArray85[] = { diag::ext_anonymous_struct, diag::ext_anonymous_union, diag::ext_flexible_array_empty_aggregate_gnu, diag::ext_flexible_array_init, diag::ext_flexible_array_union_gnu, diag::ext_forward_ref_enum_def, diag::ext_gnu_address_of_label, diag::ext_gnu_case_range, diag::ext_gnu_conditional_expr, diag::ext_gnu_empty_initializer, diag::ext_gnu_indirect_goto, diag::ext_gnu_local_label, diag::ext_gnu_statement_expr, diag::ext_in_class_initializer_float_type, diag::ext_qualified_function_type_template_arg, diag::ext_typecheck_expression_not_constant_but_accepted, diag::ext_variable_sized_type_in_struct, -1 };
static const short DiagSubGroup85[] = { 86, 240, -1 };
static const short DiagArray86[] = { diag::ext_gnu_array_range, diag::ext_gnu_missing_equal_designator, diag::ext_gnu_old_style_field_designator, -1 };
static const short DiagArray87[] = { diag::warn_using_directive_in_header, -1 };
static const short DiagArray88[] = { diag::warn_condition_is_idiomatic_assignment, -1 };
static const short DiagArray89[] = { diag::warn_qual_return_type, -1 };
static const short DiagSubGroup90[] = { 92, 93, -1 };
static const short DiagArray91[] = { diag::warn_auto_implicit_atomic_property, diag::warn_implicit_atomic_property, -1 };
static const short DiagArray92[] = { diag::ext_implicit_function_decl, diag::warn_implicit_function_decl, -1 };
static const short DiagArray93[] = { diag::ext_missing_type_specifier, -1 };
static const short DiagArray95[] = { diag::ext_nested_pointer_qualifier_mismatch, diag::ext_typecheck_convert_discards_qualifiers, diag::ext_typecheck_convert_incompatible_pointer, -1 };
static const short DiagArray96[] = { diag::warn_incomplete_impl, -1 };
static const short DiagArray98[] = { diag::warn_initializer_overrides, diag::warn_subobject_initializer_overrides, -1 };
static const short DiagArray101[] = { diag::warn_falloff_noreturn_function, diag::warn_noreturn_function_has_return_expr, -1 };
static const short DiagArray102[] = { diag::warn_offsetof_non_pod_type, -1 };
static const short DiagArray104[] = { diag::err_pp_bad_paste_ms, -1 };
static const short DiagArray105[] = { diag::ext_token_used, -1 };
static const short DiagArray106[] = { diag::warn_parameter_size, diag::warn_return_value_size, -1 };
static const short DiagArray107[] = { diag::warn_impcast_literal_float_to_integer, -1 };
static const short DiagArray108[] = { diag::warn_float_overflow, diag::warn_float_underflow, -1 };
static const short DiagArray109[] = { diag::ext_template_arg_local_type, -1 };
static const short DiagArray110[] = { diag::warn_logical_and_in_logical_or, -1 };
static const short DiagArray111[] = { diag::ext_longlong, -1 };
static const short DiagArray112[] = { diag::warn_main_one_arg, diag::warn_static_main, -1 };
static const short DiagArray113[] = { diag::err_warning_check_malformed, diag::warn_has_warning_invalid_option, -1 };
static const short DiagArray114[] = { diag::warn_non_contravariant_param_types, diag::warn_non_covariant_ret_types, -1 };
static const short DiagArray115[] = { diag::ext_anonymous_record_with_type, diag::ext_enumerator_too_large, diag::ext_flexible_array_empty_aggregate_ms, diag::ext_flexible_array_union_ms, diag::ext_function_specialization_in_class, diag::ext_ms_anonymous_struct, diag::ext_ms_enum_fixed_underlying_type, diag::ext_ms_explicit_constructor_call, diag::ext_ms_forward_ref_enum, diag::war_ms_using_declaration_inaccessible, diag::warn_found_via_dependent_bases_lookup, diag::warn_goto_into_protected_scope, diag::warn_override_exception_spec, diag::warn_pure_function_definition, -1 };
static const short DiagArray116[] = { diag::warn_struct_class_previous_tag_mismatch, diag::warn_struct_class_tag_mismatch, -1 };
static const short DiagArray117[] = { diag::warn_missing_braces, -1 };
static const short DiagArray118[] = { diag::ext_no_declarators, diag::ext_typedef_without_a_name, -1 };
static const short DiagArray119[] = { diag::warn_missing_field_initializers, -1 };
static const short DiagArray122[] = { diag::warn_missing_method_return_type, -1 };
static const short DiagArray123[] = { diag::warn_suggest_noreturn_block, diag::warn_suggest_noreturn_function, -1 };
static const short DiagArray124[] = { diag::warn_missing_prototype, -1 };
static const short DiagArray125[] = { diag::warn_module_build, -1 };
static const short DiagSubGroup126[] = { 41, 42, 56, 75, 90, 116, 117, 127, 164, 166, 168, 202, 182, 209, 217, 218, 224, 241, 139, 150, -1 };
static const short DiagArray127[] = { diag::ext_multichar_character_literal, -1 };
static const short DiagArray129[] = { diag::ext_no_newline_eof, -1 };
static const short DiagSubGroup130[] = { 179, 49, 108, -1 };
static const short DiagArray131[] = { diag::warn_cannot_pass_non_pod_arg_to_vararg, diag::warn_second_parameter_to_va_arg_not_pod, diag::warn_second_parameter_to_va_arg_ownership_qualified, -1 };
static const short DiagArray132[] = { diag::warn_non_virtual_dtor, -1 };
static const short DiagArray133[] = { diag::warn_synthesized_ivar_access, -1 };
static const short DiagArray134[] = { diag::warn_null_arg, -1 };
static const short DiagArray136[] = { diag::warn_null_in_arithmetic_operation, diag::warn_null_in_comparison_operation, -1 };
static const short DiagArray137[] = { diag::warn_indirection_through_null, -1 };
static const short DiagArray138[] = { diag::warn_type_mismatch_continuation_class, -1 };
static const short DiagArray139[] = { diag::warn_objc_missing_super_dealloc, diag::warn_objc_missing_super_finalize, -1 };
static const short DiagArray140[] = { diag::warn_objc_property_retain_of_block, -1 };
static const short DiagArray141[] = { diag::warn_objc_pointer_cxx_catch_fragile, -1 };
static const short DiagArray142[] = { diag::warn_atomic_property_nontrivial_assign_op, -1 };
static const short DiagArray143[] = { diag::warn_owning_getter_rule, -1 };
static const short DiagArray144[] = { diag::warn_category_method_impl_match, -1 };
static const short DiagArray147[] = { diag::ext_out_of_line_declaration, -1 };
static const short DiagArray149[] = { diag::ext_string_too_long, -1 };
static const short DiagArray150[] = { diag::warn_overloaded_virtual, -1 };
static const short DiagArray151[] = { diag::warn_conflicting_overriding_param_modifiers, diag::warn_conflicting_overriding_param_types, diag::warn_conflicting_overriding_ret_type_modifiers, diag::warn_conflicting_overriding_ret_types, diag::warn_conflicting_overriding_variadic, diag::warn_non_contravariant_overriding_param_types, diag::warn_non_covariant_overriding_ret_types, -1 };
static const short DiagArray152[] = { diag::warn_unnecessary_packed, -1 };
static const short DiagArray153[] = { diag::warn_padded_struct_anon_field, diag::warn_padded_struct_field, diag::warn_padded_struct_size, -1 };
static const short DiagArray154[] = { diag::warn_condition_is_assignment, diag::warn_precedence_bitwise_rel, diag::warn_precedence_conditional, -1 };
static const short DiagSubGroup154[] = { 110, 25, 155, -1 };
static const short DiagArray155[] = { diag::warn_equality_with_extra_parens, -1 };
static const short DiagArray156[] = { diag::ext_gnu_ptr_func_arith, diag::ext_gnu_subscript_void_type, diag::ext_gnu_void_ptr, diag::ext_sizeof_function_type, diag::ext_sizeof_void_type, -1 };
static const short DiagArray157[] = { diag::ext_typecheck_convert_incompatible_pointer_sign, -1 };
static const short DiagArray159[] = { diag::warn_typecheck_cond_incompatible_pointers, -1 };
static const short DiagArray160[] = { diag::ext_predef_outside_function, -1 };
static const short DiagArray161[] = { diag::warn_unimplemented_protocol_method, -1 };
static const short DiagArray162[] = { diag::warn_objc_property_attr_mutually_exclusive, -1 };
static const short DiagArray164[] = { diag::warn_initializer_out_of_order, -1 };
static const short DiagArray165[] = { diag::warn_ret_addr_label, diag::warn_ret_local_temp_addr, diag::warn_ret_local_temp_ref, diag::warn_ret_stack_addr, diag::warn_ret_stack_ref, -1 };
static const short DiagArray166[] = { diag::ext_return_has_expr, diag::ext_return_missing_expr, diag::warn_falloff_nonvoid_function, diag::warn_maybe_falloff_nonvoid_function, diag::warn_return_missing_expr, -1 };
static const short DiagArray167[] = { diag::warn_unimplemented_selector, -1 };
static const short DiagArray168[] = { diag::warn_self_assignment, -1 };
static const short DiagArray169[] = { diag::warn_semicolon_before_method_body, -1 };
static const short DiagArray170[] = { diag::warn_missing_sentinel, diag::warn_not_enough_argument, -1 };
static const short DiagArray172[] = { diag::warn_decl_shadow, -1 };
static const short DiagArray173[] = { diag::warn_ivar_use_hidden, -1 };
static const short DiagArray174[] = { diag::warn_shift_negative, -1 };
static const short DiagArray175[] = { diag::warn_shift_gt_typewidth, -1 };
static const short DiagArray176[] = { diag::warn_shift_result_gt_typewidth, -1 };
static const short DiagArray177[] = { diag::warn_shift_result_sets_sign_bit, -1 };
static const short DiagArray178[] = { diag::warn_impcast_integer_64_32, -1 };
static const short DiagArray179[] = { diag::warn_mixed_sign_comparison, -1 };
static const short DiagArray180[] = { diag::warn_impcast_integer_sign, diag::warn_impcast_integer_sign_conditional, -1 };
static const short DiagArray182[] = { diag::warn_sizeof_array_param, -1 };
static const short DiagArray183[] = { diag::warn_sizeof_pointer_expr_memaccess, diag::warn_sizeof_pointer_type_memaccess, -1 };
static const short DiagArray197[] = { diag::warn_strict_multiple_method_decl, -1 };
static const short DiagArray198[] = { diag::warn_stringcompare, -1 };
static const short DiagArray199[] = { diag::warn_impcast_string_literal_to_bool, -1 };
static const short DiagArray200[] = { diag::warn_strlcpycat_wrong_size, -1 };
static const short DiagArray201[] = { diag::ext_typecheck_base_super, -1 };
static const short DiagArray202[] = { diag::warn_case_value_overflow, -1 };
static const short DiagSubGroup202[] = { 204, -1 };
static const short DiagArray204[] = { diag::warn_missing_case1, diag::warn_missing_case2, diag::warn_missing_case3, diag::warn_missing_cases, diag::warn_not_in_enum, -1 };
static const short DiagArray206[] = { diag::warn_comparison_always, diag::warn_lunsigned_always_true_comparison, diag::warn_runsigned_always_true_comparison, -1 };
static const short DiagArray207[] = { diag::ext_typecheck_decl_incomplete_type, -1 };
static const short DiagArray208[] = { diag::note_lock_exclusive_and_shared, diag::warn_cannot_resolve_lock, diag::warn_double_lock, diag::warn_expecting_lock_held_on_loop, diag::warn_fun_excludes_mutex, diag::warn_fun_requires_lock, diag::warn_lock_at_end_of_scope, diag::warn_lock_exclusive_and_shared, diag::warn_no_unlock, diag::warn_unlock_but_no_lock, diag::warn_var_deref_requires_any_lock, diag::warn_var_deref_requires_lock, diag::warn_variable_requires_any_lock, diag::warn_variable_requires_lock, -1 };
static const short DiagArray209[] = { diag::trigraph_converted, diag::trigraph_ends_block_comment, diag::trigraph_ignored, diag::trigraph_ignored_block_comment, -1 };
static const short DiagArray211[] = { diag::warn_redefinition_of_typedef, -1 };
static const short DiagArray212[] = { diag::warn_typename_missing, -1 };
static const short DiagArray213[] = { diag::warn_undeclared_selector, -1 };
static const short DiagArray214[] = { diag::warn_pp_undef_identifier, -1 };
static const short DiagArray216[] = { diag::warn_pointer_indirection_from_incompatible_type, diag::warn_undefined_reinterpret_cast, -1 };
static const short DiagArray217[] = { diag::warn_field_is_uninit, diag::warn_uninit_self_reference_in_init, diag::warn_uninit_var, diag::warn_uninit_var_captured_by_block, -1 };
static const short DiagArray218[] = { diag::ext_on_off_switch_syntax, diag::ext_pragma_syntax_eod, diag::ext_stdc_pragma_ignored, diag::warn_pragma_diagnostic_cannot_pop, diag::warn_pragma_diagnostic_invalid, diag::warn_pragma_diagnostic_invalid_option, diag::warn_pragma_diagnostic_invalid_token, diag::warn_pragma_diagnostic_unknown_warning, diag::warn_pragma_ignored, diag::warn_stdc_fenv_access_not_supported, -1 };
static const short DiagArray219[] = { diag::warn_unknown_negative_warning_option, diag::warn_unknown_warning_option, diag::warn_unknown_warning_specifier, -1 };
static const short DiagArray220[] = { diag::ext_template_arg_unnamed_type, -1 };
static const short DiagArray221[] = { diag::warn_unneeded_internal_decl, -1 };
static const short DiagArray222[] = { diag::warn_unneeded_member_function, -1 };
static const short DiagArray223[] = { diag::warn_unreachable, -1 };
static const short DiagSubGroup224[] = { 225, 228, 229, 234, 235, -1 };
static const short DiagArray226[] = { diag::warn_unused_comparison, -1 };
static const short DiagArray227[] = { diag::warn_unused_exception_param, -1 };
static const short DiagArray228[] = { diag::warn_unused_function, -1 };
static const short DiagSubGroup228[] = { 221, -1 };
static const short DiagArray229[] = { diag::warn_unused_label, -1 };
static const short DiagArray230[] = { diag::pp_macro_not_used, -1 };
static const short DiagArray231[] = { diag::warn_unused_member_function, -1 };
static const short DiagSubGroup231[] = { 222, -1 };
static const short DiagArray232[] = { diag::warn_unused_parameter, -1 };
static const short DiagArray233[] = { diag::warn_unused_result, -1 };
static const short DiagArray234[] = { diag::warn_unused_call, diag::warn_unused_expr, diag::warn_unused_property_expr, diag::warn_unused_voidptr, -1 };
static const short DiagSubGroup234[] = { 226, 233, -1 };
static const short DiagArray235[] = { diag::warn_unused_variable, -1 };
static const short DiagArray236[] = { diag::warn_used_but_marked_unused, -1 };
static const short DiagArray237[] = { diag::warn_user_literal_hexfloat, diag::warn_user_literal_reserved, -1 };
static const short DiagArray238[] = { diag::ext_named_variadic_macro, diag::ext_variadic_macro, -1 };
static const short DiagArray239[] = { diag::warn_incompatible_vectors, -1 };
static const short DiagArray240[] = { diag::ext_vla, -1 };
static const short DiagArray242[] = { diag::warn_weak_vtable, -1 };
static const short DiagSubGroup243[] = { 60, -1 };
#endif // GET_DIAG_ARRAYS


#ifdef GET_DIAG_TABLE
  { 0, "",                                           0, DiagSubGroup0 },
  { 16, "#pragma messages",                           DiagArray1, 0 },
  { 9, "#warnings",                                  DiagArray2, 0 },
  { 16, "CFString-literal",                           DiagArray3, 0 },
  { 3, "abi",                                        0, 0 },
  { 7, "address",                                    0, 0 },
  { 20, "address-of-temporary",                       DiagArray6, 0 },
  { 16, "aggregate-return",                           0, 0 },
  { 3, "all",                                        0, DiagSubGroup8 },
  { 25, "ambiguous-member-template",                  DiagArray9, 0 },
  { 28, "analyzer-incompatible-plugin",               DiagArray10, 0 },
  { 3, "arc",                                        DiagArray11, DiagSubGroup11 },
  { 7, "arc-abi",                                    DiagArray12, 0 },
  { 21, "arc-non-pod-memaccess",                      DiagArray13, 0 },
  { 25, "arc-performSelector-leaks",                  DiagArray14, 0 },
  { 17, "arc-retain-cycles",                          DiagArray15, 0 },
  { 26, "arc-unsafe-retained-assign",                 DiagArray16, 0 },
  { 12, "array-bounds",                               DiagArray17, 0 },
  { 31, "array-bounds-pointer-arithmetic",            DiagArray18, 0 },
  { 17, "atomic-properties",                          0, DiagSubGroup19 },
  { 42, "atomic-property-with-user-defined-accessor", DiagArray20, 0 },
  { 10, "attributes",                                 DiagArray21, 0 },
  { 12, "availability",                               0, 0 },
  { 17, "bad-function-cast",                          0, 0 },
  { 22, "bind-to-temporary-copy",                     DiagArray24, 0 },
  { 22, "bitwise-op-parentheses",                     DiagArray25, 0 },
  { 16, "bool-conversions",                           DiagArray26, 0 },
  { 23, "builtin-macro-redefined",                    DiagArray27, 0 },
  { 10, "c++-compat",                                 DiagArray28, 0 },
  { 12, "c++0x-compat",                               0, DiagSubGroup29 },
  { 16, "c++0x-extensions",                           0, DiagSubGroup30 },
  { 15, "c++0x-narrowing",                            0, DiagSubGroup31 },
  { 12, "c++11-compat",                               DiagArray32, DiagSubGroup32 },
  { 16, "c++11-extensions",                           DiagArray33, 0 },
  { 15, "c++11-narrowing",                            DiagArray34, 0 },
  { 12, "c++98-compat",                               DiagArray35, 0 },
  { 21, "c++98-compat-pedantic",                      DiagArray36, DiagSubGroup36 },
  { 14, "c1x-extensions",                             DiagArray37, 0 },
  { 10, "cast-align",                                 DiagArray38, 0 },
  { 9, "cast-qual",                                  0, 0 },
  { 10, "char-align",                                 0, 0 },
  { 15, "char-subscripts",                            DiagArray41, 0 },
  { 7, "comment",                                    DiagArray42, 0 },
  { 8, "comments",                                   0, DiagSubGroup43 },
  { 22, "complex-component-init",                     DiagArray44, 0 },
  { 25, "conditional-type-mismatch",                  DiagArray45, 0 },
  { 25, "conditional-uninitialized",                  DiagArray46, 0 },
  { 19, "constant-conversion",                        DiagArray47, 0 },
  { 24, "constant-logical-operand",                   DiagArray48, 0 },
  { 10, "conversion",                                 DiagArray49, DiagSubGroup49 },
  { 17, "ctor-dtor-privacy",                          0, 0 },
  { 24, "custom-atomic-properties",                   DiagArray51, 0 },
  { 14, "dangling-field",                             DiagArray52, 0 },
  { 27, "declaration-after-statement",                DiagArray53, 0 },
  { 26, "default-arg-special-member",                 DiagArray54, 0 },
  { 22, "delegating-ctor-cycles",                     DiagArray55, 0 },
  { 23, "delete-non-virtual-dtor",                    DiagArray56, 0 },
  { 10, "deprecated",                                 DiagArray57, DiagSubGroup57 },
  { 23, "deprecated-declarations",                    DiagArray58, 0 },
  { 26, "deprecated-implementations",                 DiagArray59, 0 },
  { 27, "deprecated-writable-strings",                DiagArray60, 0 },
  { 21, "disabled-optimization",                      0, 0 },
  { 12, "discard-qual",                               0, 0 },
  { 28, "distributed-object-modifiers",               DiagArray63, 0 },
  { 11, "div-by-zero",                                0, 0 },
  { 20, "duplicate-method-arg",                       DiagArray65, 0 },
  { 23, "dynamic-class-memaccess",                    DiagArray66, 0 },
  { 6, "effc++",                                     0, 0 },
  { 10, "empty-body",                                 DiagArray68, 0 },
  { 12, "endif-labels",                               0, DiagSubGroup69 },
  { 12, "enum-compare",                               DiagArray70, 0 },
  { 21, "exit-time-destructors",                      DiagArray71, 0 },
  { 5, "extra",                                      0, DiagSubGroup72 },
  { 12, "extra-tokens",                               DiagArray73, 0 },
  { 11, "float-equal",                                DiagArray74, 0 },
  { 6, "format",                                     DiagArray75, DiagSubGroup75 },
  { 17, "format-extra-args",                          DiagArray76, 0 },
  { 24, "format-invalid-specifier",                   DiagArray77, 0 },
  { 17, "format-nonliteral",                          DiagArray78, DiagSubGroup78 },
  { 15, "format-security",                            DiagArray79, 0 },
  { 10, "format-y2k",                                 0, 0 },
  { 18, "format-zero-length",                         DiagArray81, 0 },
  { 8, "format=2",                                   0, DiagSubGroup82 },
  { 19, "four-char-constants",                        DiagArray83, 0 },
  { 19, "global-constructors",                        DiagArray84, 0 },
  { 3, "gnu",                                        DiagArray85, DiagSubGroup85 },
  { 14, "gnu-designator",                             DiagArray86, 0 },
  { 14, "header-hygiene",                             DiagArray87, 0 },
  { 21, "idiomatic-parentheses",                      DiagArray88, 0 },
  { 18, "ignored-qualifiers",                         DiagArray89, 0 },
  { 8, "implicit",                                   0, DiagSubGroup90 },
  { 26, "implicit-atomic-properties",                 DiagArray91, 0 },
  { 29, "implicit-function-declaration",              DiagArray92, 0 },
  { 12, "implicit-int",                               DiagArray93, 0 },
  { 6, "import",                                     0, 0 },
  { 26, "incompatible-pointer-types",                 DiagArray95, 0 },
  { 25, "incomplete-implementation",                  DiagArray96, 0 },
  { 9, "init-self",                                  0, 0 },
  { 21, "initializer-overrides",                      DiagArray98, 0 },
  { 6, "inline",                                     0, 0 },
  { 19, "int-to-pointer-cast",                        0, 0 },
  { 16, "invalid-noreturn",                           DiagArray101, 0 },
  { 16, "invalid-offsetof",                           DiagArray102, 0 },
  { 11, "invalid-pch",                                0, 0 },
  { 19, "invalid-token-paste",                        DiagArray104, 0 },
  { 24, "language-extension-token",                   DiagArray105, 0 },
  { 19, "large-by-value-copy",                        DiagArray106, 0 },
  { 18, "literal-conversion",                         DiagArray107, 0 },
  { 13, "literal-range",                              DiagArray108, 0 },
  { 24, "local-type-template-args",                   DiagArray109, 0 },
  { 22, "logical-op-parentheses",                     DiagArray110, 0 },
  { 9, "long-long",                                  DiagArray111, 0 },
  { 4, "main",                                       DiagArray112, 0 },
  { 23, "malformed-warning-check",                    DiagArray113, 0 },
  { 17, "method-signatures",                          DiagArray114, 0 },
  { 9, "microsoft",                                  DiagArray115, 0 },
  { 15, "mismatched-tags",                            DiagArray116, 0 },
  { 14, "missing-braces",                             DiagArray117, 0 },
  { 20, "missing-declarations",                       DiagArray118, 0 },
  { 26, "missing-field-initializers",                 DiagArray119, 0 },
  { 24, "missing-format-attribute",                   0, 0 },
  { 20, "missing-include-dirs",                       0, 0 },
  { 26, "missing-method-return-type",                 DiagArray122, 0 },
  { 16, "missing-noreturn",                           DiagArray123, 0 },
  { 18, "missing-prototypes",                         DiagArray124, 0 },
  { 12, "module-build",                               DiagArray125, 0 },
  { 4, "most",                                       0, DiagSubGroup126 },
  { 9, "multichar",                                  DiagArray127, 0 },
  { 14, "nested-externs",                             0, 0 },
  { 11, "newline-eof",                                DiagArray129, 0 },
  { 7, "non-gcc",                                    0, DiagSubGroup130 },
  { 15, "non-pod-varargs",                            DiagArray131, 0 },
  { 16, "non-virtual-dtor",                           DiagArray132, 0 },
  { 15, "nonfragile-abi2",                            DiagArray133, 0 },
  { 7, "nonnull",                                    DiagArray134, 0 },
  { 21, "nonportable-cfstrings",                      0, 0 },
  { 15, "null-arithmetic",                            DiagArray136, 0 },
  { 16, "null-dereference",                           DiagArray137, 0 },
  { 31, "objc-continuation-property-type",            DiagArray138, 0 },
  { 24, "objc-missing-super-calls",                   DiagArray139, 0 },
  { 34, "objc-noncopy-retain-block-property",         DiagArray140, 0 },
  { 26, "objc-nonunified-exceptions",                 DiagArray141, 0 },
  { 37, "objc-property-atomic-setter-synthesis",      DiagArray142, 0 },
  { 42, "objc-property-matches-cocoa-ownership-rule", DiagArray143, 0 },
  { 35, "objc-protocol-method-implementation",        DiagArray144, 0 },
  { 14, "old-style-cast",                             0, 0 },
  { 20, "old-style-definition",                       0, 0 },
  { 23, "out-of-line-declaration",                    DiagArray147, 0 },
  { 8, "overflow",                                   0, 0 },
  { 18, "overlength-strings",                         DiagArray149, 0 },
  { 18, "overloaded-virtual",                         DiagArray150, 0 },
  { 26, "overriding-method-mismatch",                 DiagArray151, 0 },
  { 6, "packed",                                     DiagArray152, 0 },
  { 6, "padded",                                     DiagArray153, 0 },
  { 11, "parentheses",                                DiagArray154, DiagSubGroup154 },
  { 20, "parentheses-equality",                       DiagArray155, 0 },
  { 13, "pointer-arith",                              DiagArray156, 0 },
  { 12, "pointer-sign",                               DiagArray157, 0 },
  { 19, "pointer-to-int-cast",                        0, 0 },
  { 21, "pointer-type-mismatch",                      DiagArray159, 0 },
  { 38, "predefined-identifier-outside-function",     DiagArray160, 0 },
  { 8, "protocol",                                   DiagArray161, 0 },
  { 21, "readonly-setter-attrs",                      DiagArray162, 0 },
  { 15, "redundant-decls",                            0, 0 },
  { 7, "reorder",                                    DiagArray164, 0 },
  { 20, "return-stack-address",                       DiagArray165, 0 },
  { 11, "return-type",                                DiagArray166, 0 },
  { 8, "selector",                                   DiagArray167, 0 },
  { 11, "self-assign",                                DiagArray168, 0 },
  { 28, "semicolon-before-method-body",               DiagArray169, 0 },
  { 8, "sentinel",                                   DiagArray170, 0 },
  { 14, "sequence-point",                             0, 0 },
  { 6, "shadow",                                     DiagArray172, 0 },
  { 11, "shadow-ivar",                                DiagArray173, 0 },
  { 20, "shift-count-negative",                       DiagArray174, 0 },
  { 20, "shift-count-overflow",                       DiagArray175, 0 },
  { 14, "shift-overflow",                             DiagArray176, 0 },
  { 19, "shift-sign-overflow",                        DiagArray177, 0 },
  { 16, "shorten-64-to-32",                           DiagArray178, 0 },
  { 12, "sign-compare",                               DiagArray179, 0 },
  { 15, "sign-conversion",                            DiagArray180, 0 },
  { 10, "sign-promo",                                 0, 0 },
  { 21, "sizeof-array-argument",                      DiagArray182, 0 },
  { 24, "sizeof-pointer-memaccess",                   DiagArray183, 0 },
  { 15, "stack-protector",                            0, 0 },
  { 15, "strict-aliasing",                            0, 0 },
  { 17, "strict-aliasing=0",                          0, 0 },
  { 17, "strict-aliasing=1",                          0, 0 },
  { 17, "strict-aliasing=2",                          0, 0 },
  { 15, "strict-overflow",                            0, 0 },
  { 17, "strict-overflow=0",                          0, 0 },
  { 17, "strict-overflow=1",                          0, 0 },
  { 17, "strict-overflow=2",                          0, 0 },
  { 17, "strict-overflow=3",                          0, 0 },
  { 17, "strict-overflow=4",                          0, 0 },
  { 17, "strict-overflow=5",                          0, 0 },
  { 17, "strict-prototypes",                          0, 0 },
  { 21, "strict-selector-match",                      DiagArray197, 0 },
  { 14, "string-compare",                             DiagArray198, 0 },
  { 17, "string-conversion",                          DiagArray199, 0 },
  { 20, "strlcpy-strlcat-size",                       DiagArray200, 0 },
  { 27, "super-class-method-mismatch",                DiagArray201, 0 },
  { 6, "switch",                                     DiagArray202, DiagSubGroup202 },
  { 14, "switch-default",                             0, 0 },
  { 11, "switch-enum",                                DiagArray204, 0 },
  { 5, "synth",                                      0, 0 },
  { 20, "tautological-compare",                       DiagArray206, 0 },
  { 36, "tentative-definition-incomplete-type",       DiagArray207, 0 },
  { 13, "thread-safety",                              DiagArray208, 0 },
  { 9, "trigraphs",                                  DiagArray209, 0 },
  { 11, "type-limits",                                0, 0 },
  { 20, "typedef-redefinition",                       DiagArray211, 0 },
  { 16, "typename-missing",                           DiagArray212, 0 },
  { 19, "undeclared-selector",                        DiagArray213, 0 },
  { 5, "undef",                                      DiagArray214, 0 },
  { 18, "undefined-internal",                         0, 0 },
  { 26, "undefined-reinterpret-cast",                 DiagArray216, 0 },
  { 13, "uninitialized",                              DiagArray217, 0 },
  { 15, "unknown-pragmas",                            DiagArray218, 0 },
  { 22, "unknown-warning-option",                     DiagArray219, 0 },
  { 26, "unnamed-type-template-args",                 DiagArray220, 0 },
  { 29, "unneeded-internal-declaration",              DiagArray221, 0 },
  { 24, "unneeded-member-function",                   DiagArray222, 0 },
  { 16, "unreachable-code",                           DiagArray223, 0 },
  { 6, "unused",                                     0, DiagSubGroup224 },
  { 15, "unused-argument",                            0, 0 },
  { 17, "unused-comparison",                          DiagArray226, 0 },
  { 26, "unused-exception-parameter",                 DiagArray227, 0 },
  { 15, "unused-function",                            DiagArray228, DiagSubGroup228 },
  { 12, "unused-label",                               DiagArray229, 0 },
  { 13, "unused-macros",                              DiagArray230, 0 },
  { 22, "unused-member-function",                     DiagArray231, DiagSubGroup231 },
  { 16, "unused-parameter",                           DiagArray232, 0 },
  { 13, "unused-result",                              DiagArray233, 0 },
  { 12, "unused-value",                               DiagArray234, DiagSubGroup234 },
  { 15, "unused-variable",                            DiagArray235, 0 },
  { 22, "used-but-marked-unused",                     DiagArray236, 0 },
  { 21, "user-defined-literals",                      DiagArray237, 0 },
  { 15, "variadic-macros",                            DiagArray238, 0 },
  { 18, "vector-conversions",                         DiagArray239, 0 },
  { 3, "vla",                                        DiagArray240, 0 },
  { 21, "volatile-register-var",                      0, 0 },
  { 12, "weak-vtables",                               DiagArray242, 0 },
  { 13, "write-strings",                              0, DiagSubGroup243 },
#endif // GET_DIAG_TABLE


#ifdef GET_CATEGORY_TABLE
CATEGORY("", DiagCat_None)
CATEGORY("Lexical or Preprocessor Issue", DiagCat_Lexical_or_Preprocessor_Issue)
CATEGORY("Semantic Issue", DiagCat_Semantic_Issue)
CATEGORY("Parse Issue", DiagCat_Parse_Issue)
CATEGORY("Automatic Reference Counting Issue", DiagCat_Automatic_Reference_Counting_Issue)
CATEGORY("Inline Assembly Issue", DiagCat_Inline_Assembly_Issue)
CATEGORY("Modules Issue", DiagCat_Modules_Issue)
CATEGORY("Related Result Type Issue", DiagCat_Related_Result_Type_Issue)
CATEGORY("#warning Directive", DiagCat__warning_Directive)
CATEGORY("Deprecations", DiagCat_Deprecations)
CATEGORY("Format String Issue", DiagCat_Format_String_Issue)
CATEGORY("Value Conversion Issue", DiagCat_Value_Conversion_Issue)
CATEGORY("#pragma message Directive", DiagCat__pragma_message_Directive)
CATEGORY("Unused Entity Issue", DiagCat_Unused_Entity_Issue)
#endif // GET_CATEGORY_TABLE

